#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# AEGIS-SILENTIUM v1.0 — Operator Key Generation Script
# ═══════════════════════════════════════════════════════════════════════════════
# Generates:
#   - Operator ECDSA P-256 key pair  (for signing objectives / kill switch)
#   - Relay ECDSA P-256 signing key  (for ECDHE handshake signature verification)
#   - WireGuard key pairs            (core + relays)
#   - GPG symmetric key              (optional, for encrypted config bundles)
#
# These keys are separate from the TLS certificates generated by gen_certs.sh.
# Run gen_certs.sh first, then run this script.
#
# Usage:
#   bash scripts/gen_keys.sh [options]
#
# Options:
#   --out DIR        Output directory (default: ./keys/)
#   --relays N       Number of relay WireGuard key pairs to generate (default: 3)
#   --no-wg          Skip WireGuard key generation (if wg is unavailable)
#   --gpg            Also generate a GPG symmetric passphrase file
#   --help           Show this message and exit
#
# Output files:
#   keys/operator/
#       operator_key.pem     — ECDSA P-256 private key  (KEEP SECRET)
#       operator_pub.pem     — ECDSA P-256 public key   (embed in relay config)
#       operator_pub.der     — DER-encoded public key   (base64 → silentium.conf)
#   keys/relay_signing/
#       relay_signing_key.pem
#       relay_signing_pub.pem
#       relay_signing_pub.der
#   keys/wireguard/
#       core_wg_private.key  (KEEP SECRET)
#       core_wg_public.key
#       relayN_wg_private.key
#       relayN_wg_public.key
#   keys/env_additions.txt   — Lines to append to .env
#
# AUTHORIZED USE ONLY
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

log()  { echo -e "${GREEN}[✓]${RESET} $*"; }
info() { echo -e "${CYAN}[→]${RESET} $*"; }
warn() { echo -e "${YELLOW}[!]${RESET} $*"; }
die()  { echo -e "${RED}[✗]${RESET} $*" >&2; exit 1; }

# ── Defaults ───────────────────────────────────────────────────────────────────
OUT_DIR="./keys"
RELAY_COUNT=3
SKIP_WG=false
GPG_KEY=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --out)     OUT_DIR="$2";     shift ;;
        --relays)  RELAY_COUNT="$2"; shift ;;
        --no-wg)   SKIP_WG=true ;;
        --gpg)     GPG_KEY=true ;;
        --help|-h)
            sed -n '2,50p' "$0" | sed 's/^# \?//'
            exit 0 ;;
        *) die "Unknown option: $1" ;;
    esac
    shift
done

command -v openssl &>/dev/null || die "openssl not found.  Install OpenSSL >= 1.1."
command -v base64  &>/dev/null || die "base64 utility not found."

mkdir -p "${OUT_DIR}"/{operator,relay_signing,wireguard}
chmod 700 "${OUT_DIR}"

echo -e "${CYAN}${BOLD}"
cat << 'BANNER'
    ___    ______ ___________
   /   |  / ____// ____/  _/
  / /| | / __/  / / __ / /
 / ___ |/ /___ / /_/ // /
/_/  |_/_____/ \____/___/
  SILENTIUM v5.0 — Key Generation
BANNER
echo -e "${RESET}"
echo ""

# ────────────────────────────────────────────────────────────────────────────
# 1. Operator ECDSA P-256 key pair
# ────────────────────────────────────────────────────────────────────────────
echo -e "${BOLD}[1/3] Generating Operator ECDSA P-256 key pair...${RESET}"

OP_KEY="${OUT_DIR}/operator/operator_key.pem"
OP_PUB="${OUT_DIR}/operator/operator_pub.pem"
OP_DER="${OUT_DIR}/operator/operator_pub.der"

openssl ecparam -name prime256v1 -genkey -noout -out "${OP_KEY}"
chmod 600 "${OP_KEY}"

openssl ec -in "${OP_KEY}" -pubout -out "${OP_PUB}" 2>/dev/null
openssl ec -in "${OP_KEY}" -pubout -outform DER -out "${OP_DER}" 2>/dev/null

OP_PUB_B64=$(base64 -w 0 "${OP_DER}" 2>/dev/null || base64 "${OP_DER}" | tr -d '\n')

log "operator_key.pem  ← KEEP THIS SECRET, never commit"
log "operator_pub.pem  ← embed in relay YAML as operator_pubkey"
log "operator_pub.der  ← base64 below for silentium.conf"
echo ""
echo -e "  ${YELLOW}Add to configs/silentium.conf [emergency] section:${RESET}"
echo -e "  operator_pubkey = ${OP_PUB_B64}"
echo ""

# ────────────────────────────────────────────────────────────────────────────
# 2. Relay ECDSA signing key (for ECDHE handshake authentication)
# ────────────────────────────────────────────────────────────────────────────
echo -e "${BOLD}[2/3] Generating Relay ECDSA signing key...${RESET}"

RS_KEY="${OUT_DIR}/relay_signing/relay_signing_key.pem"
RS_PUB="${OUT_DIR}/relay_signing/relay_signing_pub.pem"
RS_DER="${OUT_DIR}/relay_signing/relay_signing_pub.der"

openssl ecparam -name prime256v1 -genkey -noout -out "${RS_KEY}"
chmod 600 "${RS_KEY}"

openssl ec -in "${RS_KEY}" -pubout -out "${RS_PUB}" 2>/dev/null
openssl ec -in "${RS_KEY}" -pubout -outform DER -out "${RS_DER}" 2>/dev/null

RS_PUB_B64=$(base64 -w 0 "${RS_DER}" 2>/dev/null || base64 "${RS_DER}" | tr -d '\n')

log "relay_signing_key.pem → place at relay_signing_key path in relay YAML"
log "relay_signing_pub.pem → place at relay_signing_pub path in relay YAML"
echo ""
echo -e "  ${YELLOW}Add to .env:${RESET}"
echo -e "  RELAY_SIGNING_PUBKEY_B64=${RS_PUB_B64}"
echo ""

# ────────────────────────────────────────────────────────────────────────────
# 3. WireGuard key pairs
# ────────────────────────────────────────────────────────────────────────────
echo -e "${BOLD}[3/3] WireGuard key pairs...${RESET}"

if $SKIP_WG; then
    warn "Skipping WireGuard key generation (--no-wg)"
elif command -v wg &>/dev/null; then
    # Core
    CORE_PRIV="${OUT_DIR}/wireguard/core_wg_private.key"
    CORE_PUB="${OUT_DIR}/wireguard/core_wg_public.key"
    wg genkey | tee "${CORE_PRIV}" | wg pubkey > "${CORE_PUB}"
    chmod 600 "${CORE_PRIV}"
    log "Core WireGuard keys generated"
    echo "  Core public key: $(cat "${CORE_PUB}")"

    RELAY_PUBKEYS=()
    for i in $(seq 1 "${RELAY_COUNT}"); do
        RPRIV="${OUT_DIR}/wireguard/relay${i}_wg_private.key"
        RPUB="${OUT_DIR}/wireguard/relay${i}_wg_public.key"
        wg genkey | tee "${RPRIV}" | wg pubkey > "${RPUB}"
        chmod 600 "${RPRIV}"
        RELAY_PUBKEYS+=("$(cat "${RPUB}")")
        log "Relay${i} WireGuard keys generated"
        echo "  Relay${i} public key: ${RELAY_PUBKEYS[$((i-1))]}"
    done

    # Update wireguard template
    WG_TEMPLATE="${ROOT_DIR:-..}/wireguard/wg0.conf.template"
    if [[ -f "${WG_TEMPLATE}" ]]; then
        info "Updating wireguard template with generated public keys..."
        CORE_PUBKEY_VAL="$(cat "${CORE_PUB}")"
        sed -i "s|CORE_PRIVATE_KEY_PLACEHOLDER|$(cat "${CORE_PRIV}")|g" "${WG_TEMPLATE}.generated" \
            2>/dev/null || true
        cp "${WG_TEMPLATE}" "${OUT_DIR}/wireguard/wg0.conf.core"
        sed -i "s|CORE_PRIVATE_KEY_PLACEHOLDER|$(cat "${CORE_PRIV}")|" \
            "${OUT_DIR}/wireguard/wg0.conf.core"
        for i in $(seq 1 "${RELAY_COUNT}"); do
            RKEY="${RELAY_PUBKEYS[$((i-1))]}"
            sed -i "s|RELAY${i}_PUBLIC_KEY_PLACEHOLDER|${RKEY}|" \
                "${OUT_DIR}/wireguard/wg0.conf.core"
        done
        log "Generated: ${OUT_DIR}/wireguard/wg0.conf.core"
    fi
else
    warn "wireguard-tools (wg) not found — skipping WireGuard key generation"
    warn "Install with: apt install wireguard-tools  or  brew install wireguard-tools"
    warn "Then run:     wg genkey | tee private.key | wg pubkey > public.key"
fi

# ────────────────────────────────────────────────────────────────────────────
# 4. GPG passphrase (optional, for encrypted config bundles)
# ────────────────────────────────────────────────────────────────────────────
if $GPG_KEY; then
    echo ""
    echo -e "${BOLD}[4/4] Generating GPG symmetric passphrase...${RESET}"
    GPG_PASS_FILE="${OUT_DIR}/gpg_passphrase.txt"
    # Generate a strong random passphrase
    PASSPHRASE=$(openssl rand -base64 32 | tr -d '=+/' | head -c 32)
    echo "${PASSPHRASE}" > "${GPG_PASS_FILE}"
    chmod 600 "${GPG_PASS_FILE}"
    log "GPG passphrase saved to ${GPG_PASS_FILE}  (KEEP SECRET)"
    echo -e "  ${YELLOW}Use when encrypting config bundles:${RESET}"
    echo -e "  gpg --symmetric --passphrase-file ${GPG_PASS_FILE} configs/silentium.conf"
fi

# ────────────────────────────────────────────────────────────────────────────
# Write env_additions.txt
# ────────────────────────────────────────────────────────────────────────────
ENV_ADDITIONS="${OUT_DIR}/env_additions.txt"
cat > "${ENV_ADDITIONS}" << ENVEOF
# ── Append these to your .env file ──────────────────────────────────────────
# Generated by scripts/gen_keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
OPERATOR_PUBKEY_DER_B64=${OP_PUB_B64}
RELAY_SIGNING_PUBKEY_B64=${RS_PUB_B64}
ENVEOF
log "env additions written to ${ENV_ADDITIONS}"

# ── Summary ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════════════════${RESET}"
echo -e "${BOLD}${GREEN} Key generation complete!${RESET}"
echo ""
echo -e "  Output directory: ${OUT_DIR}/"
echo ""
echo -e "  ${RED}${BOLD}SECURITY REMINDERS:${RESET}"
echo -e "  • Keep operator_key.pem and relay_signing_key.pem SECRET"
echo -e "  • NEVER commit keys/ to version control (it's in .gitignore)"
echo -e "  • Copy the env_additions.txt lines into your .env file"
echo -e "  • Rotate keys periodically (recommended: every 90 days)"
echo ""
echo -e "  Next: bash scripts/gen_certs.sh --out ./certs"
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════════════════${RESET}"
